SELECT A.ANIMAL_ID, A.NAME
  FROM   (SELECT I.ANIMAL_ID, I.NAME, (O.DATETIME - I.DATETIME) AS THEDATE 
     FROM ANIMAL_INS I
     JOIN ANIMAL_OUTS O
       ON  I.ANIMAL_ID  = O.ANIMAL_ID 
    ORDER BY  THEDATE DESC
  ) AS A
 LIMIT 2;