WITH RECURSIVE ECOLI_TREE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
      FROM ECOLI_DATA
     WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, T.GENERATION + 1 AS GENERATION
      FROM ECOLI_DATA E
      JOIN ECOLI_TREE T ON E.PARENT_ID = T.ID
                             )
SELECT COUNT(T.ID) AS COUNT,T.GENERATION
  FROM ECOLI_TREE T
  LEFT JOIN ECOLI_DATA C ON T.ID = C.PARENT_ID
 WHERE C.ID IS NULL 
 GROUP BY T.GENERATION
 ORDER BY T.GENERATION ASC;