SELECT U.USER_ID, U.NICKNAME, B.SUM_PRICE
  FROM (SELECT WRITER_ID, SUM(PRICE) AS SUM_PRICE
          FROM USED_GOODS_BOARD
         WHERE STATUS = 'DONE'
         GROUP BY WRITER_ID
       ) B
  JOIN USED_GOODS_USER U
    ON B.WRITER_ID = U.USER_ID
 WHERE B.SUM_PRICE >= 700000
 ORDER BY B.SUM_PRICE;
   