SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
  FROM ITEM_TREE T
  JOIN ITEM_INFO I 
    ON T.PARENT_ITEM_ID = I.ITEM_ID
  JOIN ITEM_INFO A 
    ON T.ITEM_ID = A.ITEM_ID
 WHERE I.RARITY = 'RARE'
 ORDER BY A.ITEM_ID DESC;