WITH SKILLS AS (
    SELECT SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FRONT_END,
           SUM(CASE WHEN NAME = 'Python' THEN CODE ELSE 0 END) AS PYTHON,
           SUM(CASE WHEN NAME = 'C#' THEN CODE ELSE 0 END) AS C_SHARP
      FROM SKILLCODES
               ),
GRADE_DEV AS (
    SELECT CASE WHEN (SKILL_CODE & FRONT_END) > 0 AND (SKILL_CODE & PYTHON) > 0 THEN 'A'
                WHEN (SKILL_CODE & C_SHARP) > 0 THEN 'B'
                WHEN (SKILL_CODE & FRONT_END) > 0 THEN 'C'
            END AS GRADE,
            ID,
            EMAIL
     FROM DEVELOPERS, SKILLS
)

SELECT GRADE, ID, EMAIL
  FROM GRADE_DEV
 WHERE GRADE IS NOT NULL
 ORDER BY GRADE ASC, ID ASC;